version: "3.9"

services:
  db:
    image: postgres:16
    container_name: transguard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transguard
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./phase1/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./phase1/security.sql:/docker-entrypoint-initdb.d/02_security.sql

  adminer:
    image: adminer
    container_name: transguard-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
